### ISSUE TITLE
Error when restoring a course backup containing block instance on PHP 7.1

### ISSUE THREAD

**Issue by logan-reynolds** [roelmann/moodle-block_course_contacts#14]
Encountering the following error when testing either version 2017070100 or 2017100100 on Moodle 3.0 when attempting to restore a course backup containing an instance of block_course_contacts - UPDATE that I found this only happens when running on PHP 7.1 (i.e. even up to PHP 7.0 this is not a problem and doesn't occur):

```
Exception - Using $this when not in object context

Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 579 of /lib/pear/HTML/QuickForm.php: Error thrown
    line 545 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm::_loadElement()
    line 130 of /lib/form/dateselector.php: call to HTML_QuickForm::createElement()
    line 543 of /lib/pear/HTML/QuickForm/group.php: call to MoodleQuickForm_date_selector->_createElements()
    line 160 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_group->_createElementsIfNotExist()
    line 194 of /lib/form/dateselector.php: call to HTML_QuickForm_group->setValue()
    line 372 of /lib/pear/HTML/QuickForm/element.php: call to MoodleQuickForm_date_selector->onQuickFormEvent()
    line 414 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_element->onQuickFormEvent()
    line 215 of /lib/form/dateselector.php: call to HTML_QuickForm_group->onQuickFormEvent()
    line 579 of /lib/pear/HTML/QuickForm.php: call to MoodleQuickForm_date_selector->onQuickFormEvent()
    line 609 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm->_loadElement()
    line 199 of /backup/util/ui/base_moodleform.class.php: call to HTML_QuickForm->addElement()
    line 818 of /backup/util/ui/restore_ui_stage.class.php: call to base_moodleform->add_settings()
    line 137 of /backup/util/ui/base_ui_stage.class.php: call to restore_ui_stage_schema->initialise_stage_form()
    line 384 of /backup/util/ui/restore_ui.class.php: call to base_ui_stage->display()
    line 129 of /backup/restore.php: call to restore_ui->display()
```

Result is course restore is incomplete with some course activity modules/other content missing, so this is important that any courses containing the block instance can be safely backed up and restored restored intact

**Comment by logan-reynolds** [comment]
Apologies, as I accidentally left out the most important line that preceded that output and I've updated my comment accordingly - The _"Exception - Using $this when not in object context"_ error was seen on some other blocks as well when running on this configuration, however in testing on Moodle 3.4 I am *not* seeing the error and course restore works just fine.  So I think it's accurate to say this would only affect a limited number of people running the combination of older Moodle versions with very recent PHP 7.1 and is not a problem going forward.  Thank you for your reply and looking into this.

**Comment by roelmann** [comment]
Closing as this issue relates to testing of Moodle3.0 on PHP7.1 which is specifically not supported per Moodle docs.
