### ISSUE TITLE
Block truncates compound names

### ISSUE THREAD

**Issue by mkpelletier** [roelmann/moodle-block_course_contacts#2]
With compound surnames, the block seems to truncate the name so only the first part is shown.  E.g. if the facilitator name is something like Jacques du Plessis, you only get "Jacques Du" in the contacts block.  It would seem that the public function "shorten_name" in block_course_contacts.php has not taken into account that some names should legitimately be left intact.

**Comment by mkpelletier** [comment]
Suggested workaround: comment out lines 48-41.  The first part of the custom code for shortening names would seem to work well with hyphenated names.  However, the second part, which looks for a space in the name, does not take into account names such as those mentioned above.  In these cases, it would be better to leave such names untruncated.

**Comment by roelmann** [comment]
Does this need a solution that caters for both eventualities, such as creating such names with a non-breaking space in the first place?
Will need to look at this and consult with some colleagues more familiar with naming conventions - selecting the first part of a split last name does seem a little odd to me anyway. But at the same time to have no truncation for long names is probably not right and needs some way of dealing with it and breaking at a space as this was originally coded is the obvious one.

**Comment by mkpelletier** [comment]
Yes, I agree that a better solution is necessary, but I am not sure how to do it so that the truncation happens sensibly.  An example of abbreviation that would work well, comes from my local context, where there are a lot of Afrikaans/Dutch names.  For example, surnames consisting of: "'van der' Something" are frequently abbreviated simply as "vd Something".  However, as these kinds of abbreviations will need to be user-specified.  Perhaps this could be specified in the block settings and stored in the DB?

**Comment by mkpelletier** [comment]
Wait a second, why not use the "alternate name" field from the profile?  This would allow users to specify an alternate name or short name that could then be queried.  My guess is that this field is not used very often anyway, so it might prove useful here.

**Comment by roelmann** [comment]
I have frequently used the Alternate Name field - and for a variety of purposes, nicknames, known-as (having >10 boys named Mohammed Mohammed in a class can get challenging for official paperwork!) and others.
Usage would seem to be site/institution specific, so would be quite difficult to apply generically for a widely available plugin - although would definitely be a fairly straightforward change for an institution specific solution.

**Comment by mkpelletier** [comment]
I hadn't thought of that use case, but it certainly makes sense.  I wonder if using the alternate name field could be used via a toggle in the settings?  It seems like it should be easy enough to write.  I'll work on it and submit it in a pull request.

**Comment by roelmann** [comment]
Thanks for the pull request - now merged and will be releasing a new version with that improvement and other fixes in the next week.

**Comment by bradnielsen2981** [comment]
Why not use the css text-overflow function ellipsis to truncate names as opposed to using spaces. That way the user understands it was cut off as opposed to the incorrect name. https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

**Comment by roelmann** [comment]
Because that would potentially leave a difficult to read half-name, while breaking at a space at least leaves a more readable break. At least that's the decision taken at the time. But if you want to implement it differently please feel free, the code is open source.
