### ISSUE TITLE
Undefined property: stdClass::$description

### ISSUE THREAD

**Issue by agrowe** [roelmann/moodle-block_course_contacts#21]
When testing this plugin on a Moodle 3.5 upgrade, we are seeing the below error message.

`PHP message: PHP Notice:  Undefined property: stdClass::$description in /var/www/moodle/blocks/course_contacts/block_course_contacts.php on line 268`

This is due to this line, `$this->config->description == 1` where the blocks configuration does not have a description property set, most likely from being set in a previous version.

Adding an `isset()` before checking resolves the issue for us, but you could also use `!empty()`

`if (isset($this->config->description) && $this->config->description == 1 && $contact->description != "") {`

**Comment by roelmann** [comment]
Fixed in new rewrite
