### ISSUE TITLE
Why does this block mangle people's names?

### ISSUE THREAD

**Issue by gormster** [roelmann/moodle-block_course_contacts#24]
I've seen #2 - I know there's a workaround for this, although in my opinion, not an ideal one: this is abusing the "alternate name" feature, which is designed to help people with different names in their native tongue to the course language. This workaround suggests creating an alternate name that is identical to the user's `fullname`…

My question is why? Why on earth would you want to mess around with people's names? It seems like you are begging to be kicked by one of the items on [this list](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). Which indeed you are, with our many users with a space in their first or last name!

It just doesn't seem like it could possibly be justified. The user is referred to by their `fullname` everywhere else in Moodle. If they want to be listed by a different name in Course Contacts, that would be the exception, not the rule - that would be the time to use `alternatename`.

At the very least, this needs to be a setting, but realistically, it should be removed, and the alternate name setting retained for users who want a different name to be presented.

**Comment by roelmann** [comment]
Honest answer - it was in the code I inherited and I've never sorted it out, and right now don't have the time to investigate it.
The solution I have in my mind is fairly straightforward in terms of simply doing a string replace for any spaces with non-breaking spaces anyway. But this does not address the display of long names within the block.

However, feel free to make a pull request and suggest a code change to integrate, but please bear in mind the reason why the original code is there - some names are too long to comfortably fit in a block, although they may fit in other less restricted areas within Moodle. Any suggested change would need to find a way to adequately deal with displaying those long names.

**Comment by roelmann** [comment]
No pull request forthcoming, so closing issue.

**Comment by roelmann** [comment]
I believe this has become less of an issue with various style changes and names appear now to wrap appropriately even when they are very long, so I am removing the shortening function completely.
