### ISSUE TITLE
standard capability block/course_contacts:myaddinstance not defined

### ISSUE THREAD

**Issue by savva312** [roelmann/moodle-block_course_contacts#6]
I get this warning on Moodle 3.3

he block course_contacts does not define the standard capability block/course_contacts:myaddinstance
line 595 of /blocks/moodleblock.class.php: call to debugging()
line 567 of /blocks/moodleblock.class.php: call to block_base->has_add_block_capability()
line 228 of /lib/blocklib.php: call to block_base->user_can_addto()
line 3806 of /lib/navigationlib.php: call to block_manager->get_addable_blocks()
line 771 of /lib/pagelib.php: call to flat_navigation->initialise()
line 820 of /lib/pagelib.php: call to moodle_page->magic_get_flatnav()
line 47 of /theme/boostunic/layout/columns2.php: call to moodle_page->__get()
line 1162 of /lib/outputrenderers.php: call to include()
line 1092 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of /my/index.php: call to core_renderer->header()

**Comment by roelmann** [comment]
Fixed by https://github.com/roelmann/moodle-block_course_contacts/commit/f5196e0f13c336895c9bfb81f552cf103d7f5d1f
Thanks Savva312
